class Exit(Exception):
    pass

class Fail(Exception):
    pass
